import * as p2 from './problem2/problem'
import * as p4 from './problem4/problem'
import * as p6 from './problem6/problem'
import * as p8 from './problem8/problem'
import * as p10 from './problem10/problem'